version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./.env
    platform: linux/arm64
    volumes:
      - ./vol:/app/prod-errors

  redis:
    image: redis:alpine
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: